### PR TITLE
fix for tinder-access-token-generator v2.1.0

### PR DESCRIPTION
**Pull request by unixpickle**

### CODE REVIEW

**Comment by jaebradley** [comment]
@unixpickle thanks for opening this PR!

I _think_ this should be fine and I see some rationale for this - out of curiosity did you find the name confusing?

**Comment by unixpickle** [comment]
`createClientFromFacebookLogin` wasn't working for me, because it used the wrong method from tinder-access-token-generator. This should fix that.

**Comment by jaebradley** [comment]
@unixpickle isn't this just renaming the default export? This shouldn't impact the underlying logic, correct?

(For reference, [this should be the default export for `v2.0.0`](https://github.com/jaebradley/tinder-access-token-generator/blob/9c6dbface274bbb67ba4626647edb41cd659fddb/src/index.js#L5-L25)).

**Comment by unixpickle** [comment]
Sorry about the initial PR not fixing the problem. This diff should now work.

When you npm install tinder-client, it pulls in tinder-access-token-generator v2.1.0, not v2.0.0, and the exports are different (see 2.1.0's [index.js](https://github.com/jaebradley/tinder-access-token-generator/blob/v2.1.0/src/index.js)). This change shouldn't have been made to tinder-access-token-generator in a minor version release, since it seems to be a breaking change.

**Comment by jaebradley** [comment]
@unixpickle sorry about the delay in getting back to you.

As you saw from the referenced comments, I attempted to resolve this in #112 by explicitly pinning the `tinder-access-token-generator` to version `2.0.0`.

As you correctly pointed out, `2.1.0` should have been a major version update - this is something I messed up when releasing the changes associated with `2.1.0` (and also why the changes associated with `3.0.0` are identical).

I probably should've deleted the version in `npm`, but I figured it was safe as is, forgetting that the version defined in `tinder-client` was unpinned.

I have since deprecated `tinder-access-token-generator@2.1.0`.

Sorry about any issues you've run into, and thanks for reporting the issue in the first place.

**Pull request closed without merging**
